name: testnm
favicon: null
layout_spectrum: 0.6909125263337046
typography_spectrum: 0.9011775066610426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#070e1e'
    - '#305b9f'
    - '#0b2757'
    - '#1c437a'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
